FROM alpine:3 as builder

RUN apk add --no-cache vips-dev boost-dev cmake g++ make



WORKDIR /app
COPY CMakeLists.txt .
COPY src src
COPY vendor vendor

WORKDIR /app/build
RUN cmake -DCMAKE_BUILD_TYPE=Release .. && make -j

FROM alpine:3

RUN apk add --no-cache vips


WORKDIR /app
COPY --from=builder /app/build/asset-server .

ENTRYPOINT [ "./asset-server" ]
