FROM debian:bookworm

RUN apt update \
 && apt install libmagick++-dev libboost-dev cmake g++ make --no-install-recommends -y \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY CMakeLists.txt .
COPY src src
COPY vendor vendor

WORKDIR /app/build
RUN cmake -DCMAKE_BUILD_TYPE=Release .. && make -j

ENTRYPOINT [ "./asset-server" ]
